/**
 * TestApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ActiveRoadShipmentDraft { 
    id: string;
    bookingMode?: string;
    warehouse?: string;
    freightType?: string;
    shipmentId?: string;
    poNumber?: string;
    contract?: string;
    todaysDate?: Date;
    loadingDateSelection?: number;
    loadingDate?: Date;
    unloadingDateSelection?: string;
    unloadingDate?: Date;
    loadingTimeSelection?: string;
    loadingTimeFrom?: string;
    loadingTimeTo?: string;
    unloadingTimeSelection?: string;
    unloadingTimeFrom?: string;
    unloadingTimeTo?: string;
    sender?: string;
    receiver?: string;
    loadingAddress?: string;
    unloadingAddress?: string;
    loadingReference?: string;
    unloadingReference?: string;
    loadingInstructions?: string;
    unloadingInstructions?: string;
    incoterm?: string;
    customsRequired?: boolean;
    customsDocumentsLocation?: string;
    customsDocumentsInstructions?: string;
    remarks?: string;
    fileIds: string;
    tenantId: string;
}