/**
 * TestApi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ProductStock { 
    id: string;
    name: string;
    amount: number;
    pictureId?: string;
    longNumber: number;
    allFloat: number;
    yourBlessings: number;
    ingForColumbine: boolean;
    mander: string;
    beginning: Date;
}